version: 2
models:
  - name: stg_orders
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          arguments:
            min_value: 1
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: amount
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                strictly: true
      - name: status
        tests:
          - accepted_values:
              values: ['created','paid','cancelled','refunded']
      - name: customer_email
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
              arguments:
                regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      - name: event_time
        tests: [not_null]

  - name: stg_payments
    columns:
      - name: payment_id
        tests: [not_null, unique]
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: amount
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                strictly: true
      - name: event_time
        tests: [not_null]

  - name: stg_orders_with_delay
    columns:
      - name: event_delay_minutes
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10
