services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
    - "1883:1883"
    volumes:
    - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./sink_api/db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  api:
    build: ./sink_api
    container_name: sink_api
    env_file: .env
    ports:
    - "${API_PORT}:8000"