apiVersion: 1

datasources:
  - name: Postgres (IoT)
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false